### ISSUE TITLE
Received "Resource was not found" message

### ISSUE THREAD

**Issue by ghost** [fuel9/DisplayMonkey#67] opened 2018-09-12 14:18 UTC
Hi,

I have successfully setup DisplayMonkey to show for client computers but when trying to load the Management page I receive:
"An error occured while processing your request.
Details
Message Resource was not found"

Please can someone advise what I need to do to resolve?

Attached: Management=Page.png & Client-Page.png

![client-page](https://user-images.githubusercontent.com/43211010/45431215-1b5dfd80-b69f-11e8-96b7-8a6b2b523a03.PNG)

![management-page](https://user-images.githubusercontent.com/43211010/45431163-fbc6d500-b69e-11e8-81c9-57da2f70ca1a.PNG)

**Comment by michaelmalmgren** [comment] 2018-09-13 14:06
Hi,

It looks like you're missing one or more steps in the installation(?). Have you configured the app to use windows authentication? Is the app running in a .net 4.5 application pool?

/M

**Comment by michaelmalmgren** [comment] 2018-09-13 14:06
Btw, here is a link to the install instruction in case you need it: http://www.displaymonkey.org/dm/documentation/installation/

**Comment by jasyapan** [comment] 2018-09-13 14:21
Thank you for your response.

Yes, Windows Authentication for the DisplayMonkey_Management app is Enabled and the application pool is set to ASP.NET V4.0. These settings are mirrored from DisplayMonkey app, which loads successfully.

I have tried the application pool on DefaultAppPool, ran issreset & tried again but I still receive the same error message.

**Comment by michaelmalmgren** [comment] 2018-09-14 07:59
Can you look in your IIS logs (should be here by default: C:\inetpub\logs\LogFiles) if there is more information on the error?

**Comment by jasyapan** [comment] 2018-09-14 10:20
I have attached the log file, if you can make head or tails of it.

[u_ex180914.log](https://github.com/fuel9/DisplayMonkey/files/2382939/u_ex180914.log)

**Comment by psined1** [comment] 2018-10-09 15:50
OP: it has been a while, can this be closed now?

**Comment by jasyapan** [comment] 2018-10-10 07:00
Fine.
Not that this has been resolved...

**Comment by psined1** [comment] 2018-10-23 15:15
Have a look at #68. Hopefully it will give you any clues.

I'm going to close this for now as there is no solid evidence of others affected by the same issue. Must be something local to your environment/installation. We are a community-based support, meaning we can only share our experiences. But we are not a full-blown support organization as you would expect from a paid service.

If you happen to pinpoint the root cause of your issue, we would appreciate you post your findings and share what you did to solve it.

Thanks for trying Display Monkey!

**Closed by psined1** 2018-10-23 15:15 UTC
Labels: help wanted

**Comment by LiamGawler** [comment] 2018-10-30 05:32
i am having the same issue aswell. has anyone been able to solve?
![image](https://user-images.githubusercontent.com/44594558/47697914-11975600-dc5d-11e8-8ea9-da1a5f422c9f.png)

[u_ex181030.log](https://github.com/fuel9/DisplayMonkey/files/2528155/u_ex181030.log)

**Comment by cooperlistic** [comment] 2019-06-19 09:36
For the DisplayMonkey_Management,  set Anonymous Authentication to Disabled.  When prompted for password upon trying to browse it, key in your windows username and password. That should do the trick . Works on IIS 10, .Net 4.5 , Windows 10.
