### ISSUE TITLE
Invalid date on BeginsOn and EndsOn form fields

### ISSUE THREAD

**Issue by systemq** [fuel9/DisplayMonkey#63] opened 2018-08-23 09:43 UTC
Hi,

 I'm trying out Display Monkey and have hit a problem with Enering dates in the memo frame for begin and end. I'm in the uk so the forms  input field calender show the firleds in a DD/MM/YYYY format. But when I enter 23/08/2018 I get an error like this:

The field Begins on must be a date.

if I change it manualy to 08/23/2018 I get this error:

The value '08/23/2018' is not valid for BeginsOn.

What do I need to do to get this from to accept dates?

Thanks,
Simon

**Comment by michaelmalmgren** [comment] 2018-08-23 15:46
Hi Simon,

I was not able to reproduce this by setting my Windows (win 7) Region and Language settings to English (United Kingdom). Is this the setting you are using on the computer that is running the browser in question?

**Comment by systemq** [comment] 2018-08-23 15:54
Hi,
Yes, using Windows 10, Language is English (United Kingdom) for keyboard, date and Time on the server and windows 7 on the computer I'm connecting with the same.

I've set in the location location i'm using, the date format of DD-MM-YYYY, is that correct?

Simon.

**Comment by michaelmalmgren** [comment] 2018-08-23 15:58
Yes, whatever date formant that you have selected on the local computer should be reflected in every form. What browser are you using?

**Comment by systemq** [comment] 2018-08-23 16:18
I've tried it on both Chrome and FireFox.

**Comment by michaelmalmgren** [comment] 2018-08-23 16:32
Simon, I was able to reproduce this issue using Chrome and setting Language setting to English (United Kingdom). Issue does not seam to exist in IE. I assume this is a bug that we need to corrected.

**Comment by systemq** [comment] 2018-08-24 08:32
Hi,

Thanks for checking that out. Didn't think to check it with IE! As you said, it worked in IE so I was able to set up some fames to be come viewable next week.

It would be nice to be able to use it in Chrome, so I will leave that with you to fix, but at least I can do the management from IE.

Thanks again,
Simon

**Comment by psined1** [comment] 2018-10-09 16:16
Possible duplicate of #30

**Closed** 2019-05-29 13:43 UTC
Labels: bug
