### ISSUE TITLE
SSRS Report Path

### ISSUE THREAD

**Issue by JamestownDistributors** [fuel9/DisplayMonkey#54] opened 2018-07-10 20:55 UTC
We are having a bear of a time trying to get this working with SSRS. 

Our Report server URL is 
http://yeti.jamestowndistributors.com/ReportServer
though we have tried 

SSRS | http://yeti.jamestowndistributors.com/ReportServer | jamestowndistributors.com\liamk | Delete
ssrs2 | http://yeti.jamestowndistributors.com/reports | jamestowndistributors.com\liamk | Delete
Yeti | https://yeti.jamestowndistributors.com/ReportServer | jamestowndistributors.com\liamk | Delete
Yeti1 | http://yeti.jamestowndistributors.com/ReportServer? | jamestowndistributors.com\liamk | Delete

From there we have tried our path. as instructed by the documentation. 

/Warehouse/Orders+Waiting+To+Be+Releaed+To+Pick

I have tried copying the url from the report page itself, not that I thought that would work. 

But even using the server url and the path in a browser as suggested by your docs only brings me to the root of the report server not the actual report. 

Anyone have any hints as the documentation does not provide a lot to go on?

**Comment by michaelmalmgren** [comment] 2018-07-11 08:36
Hi, I assume that the problem is that report isn't displayed in your presentation without any errors(?). Does other types of content work like images and html? Make sure you have the display switch "show errors" checked. Also can browse to the report from a computer displaying the report using the credentials you entered in the DM settings?

/Michael

**Comment by janicedawley** [comment] 2018-07-25 16:02
I'm having similar trouble getting SSRS reports to display. I've tried a number of variations on the base URL as well as the report URL, and no matter what, I always end up with a little broken graphic icon instead of a report in my frame.

Not sure if it's related to the issue, but our installation of SSRS is in SharePoint integrated mode, so the our base URL is in a different format than the example.

**Comment by janicedawley** [comment] 2018-07-30 20:34
Updating to add... I learned that we have a native mode installation of SSRS as well, and I tested a connection to that with similar results. No reports displaying, just a broken graphic. It would be great if someone who has gotten this working could provide some guidance.

**Comment by michaelmalmgren** [comment] 2018-08-03 09:30
Janicedawley, Can you manually browse to the report from a "Display Monkey" computer using the credentials you entered in the DM settings?

**Comment by janicedawley** [comment] 2018-08-03 14:21
Hi Michael -- Yes, I can browse to the report in both instances (SharePoint integrated mode and native mode).

**Comment by ehuels-zahner** [comment] 2018-08-14 15:43
Having the same issue.  We are running SQL 2012 SSRS in Native mode.  I have tried all sorts of combinations for the path.  Tried SSL and non-SSL. Different user accounts. Nothing is working.  This is a new installation; if I get desperate, I may try downloading and older version of DM to see if it is a problem with the current build.

**Comment by michaelmalmgren** [comment] 2018-08-15 14:31
Hi Ehuels, please verify that you are using the URL to the SSRS **server** and not the SSRS **management** portal

**Incorrect:**
Report Manager URL : http://servername/reports

**Correct:**
ReportServer URL : http://servername/reportserver

**Comment by ehuels-zahner** [comment] 2018-08-15 14:47
Yes. I am using the correct ...reportserver URL. I attempting to display a report under a folder.  I can verify that I am trying to display a report file, not a link.  Neither the report or the folder have spaces in the name.

**Comment by psined1** [comment] 2018-08-15 14:53
I'm sure you have looked already at #55 . In any event, I would highly recommend if not.

**Comment by ehuels-zahner** [comment] 2018-08-15 15:11
I believe figured out my problem.  One of those DUH moments.  I have DM installed in a Dev environment trying to view a Production report. Network config won't allow Dev to connect to Prod.  Unfortunatley I don't have SSRS available to me in Dev.

**Comment by psined1** [comment] 2018-08-15 15:33
OK, great, I'll close this one then.

**Closed by psined1** 2018-08-15 15:33 UTC
